# Generated by Django 3.1 on 2020-08-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
    ]
