# Generated by Django 3.1 on 2020-09-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200906_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='who_can_vote',
            field=models.CharField(choices=[('All Members', 'All Members'), ('Students', 'Students')], default='Students', max_length=30),
        ),
    ]
